apiVersion: apps/v1
kind: Deployment
metadata:
  name: owo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owo
  template:
    metadata:
      labels:
        app: owo
    spec:
      containers:
      - image: okteto.dev/owo:latest
        name: owo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "fc1a4bf2-02d7-9ca1-a4de-6c6a9cc424d0"
        - name: Vless_Path
          value: "/kkkvl"
        - name: Vmess_UUID
          value: "fc1a4bf2-02d7-9ca1-a4de-6c6a9cc424d0"
        - name: Vmess_Path
          value: "/kkkvm"
        - name: Share_Path
          value: "/v2link"
